### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by TillWinter** [Kripth/toml#9]
While trying to compile the Project I encounter the following Error Messages:

>/usr/bin/dub run --build-mode separate
Performing "debug" build using /usr/bin/dmd for x86_64.
toml 1.0.0-rc.3: building configuration "library"...
/usr/include/dmd/phobos/std/math.d(282,12): Error: variable `std.math.floatTraits!(inout(double)).RECIP_EPSILON` only parameters or stack based variables can be `inout`
/usr/include/dmd/phobos/std/math.d(6814,15): Error: template instance `std.math.floatTraits!(inout(double))` error instantiating
/usr/include/dmd/phobos/std/format.d(2652,27):        instantiated from here: `isInfinity!(inout(double))`
/usr/include/dmd/phobos/std/format.d(1875,20):        instantiated from here: `formatValueImpl!(Appender!string, inout(double), char)`
/usr/include/dmd/phobos/std/conv.d(1072,16):        instantiated from here: `formatValue!(Appender!string, inout(double), char)`
/usr/include/dmd/phobos/std/conv.d(222,24):        instantiated from here: `toImpl!(string, inout(double))`
src/toml/toml.d(348,40):        instantiated from here: `to!(inout(double))`
/usr/include/dmd/phobos/std/format.d(2671,31): Error: template instance `std.math.signbit!(inout(double))` error instantiating
/usr/include/dmd/phobos/std/format.d(1875,20):        instantiated from here: `formatValueImpl!(Appender!string, inout(double), char)`
/usr/include/dmd/phobos/std/conv.d(1072,16):        instantiated from here: `formatValue!(Appender!string, inout(double), char)`
/usr/include/dmd/phobos/std/conv.d(222,24):        instantiated from here: `toImpl!(string, inout(double))`
src/toml/toml.d(348,40):        instantiated from here: `to!(inout(double))`
/usr/include/dmd/phobos/std/format.d(2709,10): Error: forward reference to inferred return type of function call `function () @trusted
{
import core.stdc.stdio : snprintf;
return snprintf(buf2.ptr, buf2.length, sprintfSpec.ptr, fs.width, fs.precision == fs.UNSPECIFIED ? -1 : fs.precision, tval);
}
()`
/usr/bin/dmd failed with exit code 1.

I am using:
Compiler: DMD64  v2.090.0
Phobes: libphobos2-90

**Comment by moon-chilled** [comment]
You can fix this by changing line 348 in `src/toml/toml.d` from:

```d
immutable str = this.store.floating.to!string;
```

to

```d
immutable str = (cast(immutable)this.store.floating).to!string;
```

I think it's actually a phobos bug.
